kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wordpress-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wordpress-sc-legacy-shared
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
